### ISSUE TITLE
Improve exception handling when a jenkins instance cannot be reached.

### ISSUE THREAD

**Issue by waynr** [rji/waylon#63]
When Waylon can't reach any jenkins instances it fails with mysterious errors.

**Comment by rji** [comment]
Can you provide the log output or error messages you were seeing?

**Comment by waynr** [comment]
```
14:29:18 web.1      | [2015-01-27 14:29:18] INFO  WEBrick 1.3.1
14:29:18 web.1      | [2015-01-27 14:29:18] INFO  ruby 2.0.0 (2014-05-08) [universal.x86_64-darwin13]
14:29:18 web.1      | [2015-01-27 14:29:18] INFO  WEBrick::HTTPServer#start: pid=62595 port=5000
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /view/Puppet%20Server HTTP/1.1" 200 3298 0.0097
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/bootstrap-3.1.1.min.js HTTP/1.1" 304 - 0.0012
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/underscore-1.6.0.min.js HTTP/1.1" 304 - 0.0006
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /css/bootstrap.min.css HTTP/1.1" 304 - 0.0007
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /css/waylon.css HTTP/1.1" 200 4255 0.0064
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/jquery-2.1.1.min.js HTTP/1.1" 304 - 0.0010
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/backbone-1.1.2.min.js HTTP/1.1" 304 - 0.0010
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/handlebars-1.3.0.min.js HTTP/1.1" 304 - 0.0010
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/model/alert.js HTTP/1.1" 304 - 0.0008
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/settings.js HTTP/1.1" 304 - 0.0010
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/job.js HTTP/1.1" 200 2561 0.0015
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/model/job.js HTTP/1.1" 200 3319 0.0047
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/investigate_menu.js HTTP/1.1" 200 2981 0.0015
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/weather.js HTTP/1.1" 200 1486 0.0068
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/radiator.js HTTP/1.1" 304 - 0.0014
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/job_status_icon.js HTTP/1.1" 200 2085 0.0013
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/stats_rollup.js HTTP/1.1" 304 - 0.0138
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/job_progress.js HTTP/1.1" 304 - 0.0012
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/trouble.js HTTP/1.1" 304 - 0.0012
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/nirvana.js HTTP/1.1" 304 - 0.0011
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/collection/job_collection.js HTTP/1.1" 304 - 0.0008
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/alert.js HTTP/1.1" 200 1083 0.0017
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/view/alert_list.js HTTP/1.1" 304 - 0.0008
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/collection/alert_collection.js HTTP/1.1" 304 - 0.0010
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /js/waylon/app.js HTTP/1.1" 200 1786 0.0250
14:29:40 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:40] "GET /fonts/glyphicons-halflings-regular.woff HTTP/1.1" 304 - 0.0009
14:29:50 web.1      | Net::OpenTimeout - execution expired:
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/client.rb:278:in `make_http_request'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/client.rb:332:in `api_get_request'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/view.rb:187:in `list'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/view.rb:203:in `exists?'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/view.rb:216:in `list_jobs'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/server/rest.rb:26:in `block in job_names'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/server/rest.rb:25:in `each'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/server/rest.rb:25:in `job_names'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/server/memcached.rb:19:in `block in job_names'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/memcached.rb:12:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/memcached.rb:12:in `rescue in cache'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/memcached.rb:5:in `cache'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/server/memcached.rb:19:in `job_names'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/server/memcached.rb:23:in `jobs'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/view.rb:22:in `block in jobs'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/view.rb:21:in `map'
14:29:50 web.1      |   /Users/greenwall/waylon/lib/waylon/jenkins/view.rb:21:in `jobs'
14:29:50 web.1      |   /Users/greenwall/waylon/waylon.rb:111:in `block (3 levels) in <class:Waylon>'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:26:in `instance_exec'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:26:in `block in try'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:18:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:18:in `block in call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:17:in `each'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:17:in `inject'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:17:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:5:in `attempt_all'
14:29:50 web.1      |   /Users/greenwall/waylon/waylon.rb:109:in `block in <class:Waylon>'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
14:29:50 web.1      |   /Users/greenwall/waylon/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
14:29:50 web.1      |   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
14:29:50 web.1      | 127.0.0.1 - - [27/Jan/2015 14:29:50] "GET /api/view/Puppet%20Server/jobs.json HTTP/1.1" 500 222289 10.0930
```

**Comment by waynr** [comment]
@rji ^^

**Comment by rji** [comment]
Interesting. We've accounted for some failure modes, but I guess not `Net::OpenTimeout` specifically. Had that exception been handled properly, you should have seen https://github.com/rji/waylon/blob/5a2229d87637dddc5202ec16518fff7853efce09/public/js/waylon/app.js#L41-L46.

**Comment by rji** [comment]
This ticket probably also applies to non-existent views. If a non-existent job is queried, Waylon will display a warning; if a non-existent view is queried, the app will be unusable for that particular view.
