### ISSUE TITLE
Waylon doesn't allow for arbitrarily-nested views

### ISSUE THREAD

**Issue by rji** [rji/waylon#71]
Waylon supports the "Nested View" plugin using its `nested_view` configuration param. But nested views can only be two levels deep, whereas there is no such restriction in the actual Nested View Jenkins plugin.

**Comment by rji** [comment]
This is happening in https://github.com/rji/waylon/blob/acaf03197e593e57ceb7f9406d03377f26a1edb2/lib/waylon/jenkins/server/rest.rb#L21-L40 and/or https://github.com/rji/waylon/blob/acaf03197e593e57ceb7f9406d03377f26a1edb2/lib/jenkins_api_client/nested_view.rb

**Comment by rji** [comment]
Related stack trace:

```
2015-05-26 16:15:42 - NoMethodError - undefined method `encode' for ["Master", ["Hiera", "Facter", "Puppet", "MCO"]]:Array:
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/urihelper.rb:14:in `path_encode'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/jenkins_api_client/nested_view.rb:43:in `list_nested_jobs'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/rest.rb:32:in `block (2 levels) in job_names'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/rest.rb:30:in `each'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/rest.rb:30:in `block in job_names'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/rest.rb:29:in `each_pair'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/rest.rb:29:in `job_names'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/memcached.rb:19:in `block in job_names'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/memcached.rb:12:in `call'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/memcached.rb:12:in `rescue in cache'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/memcached.rb:5:in `cache'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/memcached.rb:19:in `job_names'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/server/memcached.rb:23:in `jobs'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/view.rb:22:in `block in jobs'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/view.rb:21:in `map'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/view.rb:21:in `jobs'
	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/waylon.rb:115:in `block (3 levels) in <class:Waylon>'
```

**Comment by rji** [comment]
Example JSON response from https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/api/json?pretty=true of a top-level "nested view" that can contain both additional views and jobs.

```json
{
  "description" : null,
  "jobs" : [
    
  ],
  "name" : "All in One Agent",
  "property" : [
    
  ],
  "url" : "https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/",
  "views" : [
    {
      "name" : "Aardwolf",
      "url" : "https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/view/Aardwolf/"
    },
    {
      "name" : "Master",
      "url" : "https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/view/Master/"
    },
    {
      "name" : "Stable",
      "url" : "https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/view/Stable/"
    }
  ]
}
```

**Comment by rji** [comment]
And it appears to stem from this method when loading the config: https://github.com/rji/waylon/blob/master/lib/waylon/config/server.rb#L30-L31
