### ISSUE TITLE
Waylon gets HTTP 500 if a job is removed

### ISSUE THREAD

**Issue by joshcooper** [rji/waylon#78]
If a job is moved from one Jenkins to another, Waylon will get an HTTP 500 and report:

```
Best check yo'self. Couldn't get info for job: 'puppet (master) Component Pipeline Step 1 -- Component Init' - Internal Server Error
```

and the err log will contain the following stack trace:

```
2016-11-28 14:46:19 - JenkinsApi::Exceptions::NotFound - Requested component is not found on the Jenkins CI server.:
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/client.rb:724:in `handle_exception'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/client.rb:336:in `api_get_request'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jenkins_api_client-1.0.1/lib/jenkins_api_client/job.rb:1027:in `get_build_details'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/job/rest.rb:77:in `last_build_display_name'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/lib/waylon/jenkins/job/rest.rb:129:in `to_hash'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/waylon.rb:129:in `block (3 levels) in <class:Waylon>'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:26:in `instance_exec'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:26:in `block in try'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:18:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:18:in `block in call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:17:in `each'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:17:in `inject'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:17:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/deterministic-0.6.0/lib/deterministic/either/attempt_all.rb:5:in `attempt_all'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/waylon-2.1.4/waylon.rb:125:in `block in <class:Waylon>'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.1/lib/rack/logger.rb:15:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.1/lib/rack/methodoverride.rb:22:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.1/lib/rack/chunked.rb:54:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:536:in `maintain_worker_count'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:294:in `join'
       	/usr/local/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
       	/usr/local/rbenv/versions/2.1.5/bin/unicorn:23:in `load'
       	/usr/local/rbenv/versions/2.1.5/bin/unicorn:23:in `<main>'
XXX - - [28/Nov/2016:14:46:19 -0800] "GET /api/view/Agent/server/XXX/job/platform_puppet_init-van-component_stable.json HTTP/1.0" 500 30 0.2790
```

memcached contains job details for the new jenkins:

```
$ echo "stats cachedump 21 1000" | nc -U /var/run/memcached/memcached.sock  | grep platform_puppet_init-van
$ echo "get job-platform_puppet_init-van-component_stable-details 0 8105" | nc -U /var/run/memcached/memcached.sock
VALUE job-platform_puppet_init-van-component_stable-details 0 8105
{
...                                                                                                                                                                 _class;TI" hudson.model.FreeStyleBuild;TI"
                  number;Ti
                           Iurl;TI"khttps://jenkins-master-prod-1.XXX/job/platform_puppet_init-van-component_stable/7/;TI"
```

But waylon still tries to retrieve job status from the old jenkins:

```
XXX - - [28/Nov/2016:14:46:48 -0800] "GET /api/view/Client/server/XXX/job/platform_puppet_init-van-component_stable.json HTTP/1.0" 500 30 0.9215
```

**Comment by joshcooper** [comment]
I think there are two different issues. First, waylon does not detect when a job is removed from a view. So it handles a request for a view, eg `/api/view/Client/jobs.json`, and then tries to query for jobs that are no longer in the view resulting in a 404:

```
10.0.17.133 - - [28/Nov/2016:17:57:24 -0800] "GET /api/view/Client/jobs.json HTTP/1.0" 200 1681 0.0156
...
10.0.27.232 - - [28/Nov/2016:17:57:35 -0800] "GET /api/view/Client/server/XXX/job/legacy_facter_unit-windows_2.x.json HTTP/1.0" 404 80 0.0151
```

Second, waylon assumes that the same job isn't on two different jenkins instances, and it appears the caching logic gets confused if that happens leading to HTTP 500.

**Comment by rji** [comment]
This is probably related to the use of memcached. Prior to introducing memcached, the state of all the jobs would be rebuilt every time Waylon polled the Jenkins masters. I'd recommend taking a look there, or disabling memcached altogether if the Jenkins masters are large enough to handle the load.

/cc @adrienthebo

**Comment by adrienthebo** [comment]
@joshcooper come bug me in person and I can see about chasing this down/fixing it, since I was the one that wrote the broken code :)
